import { writeFileSync } from "node:fs";
import { join } from "node:path";
import * as p from "@clack/prompts";
import { getError, showIntro, showOutro } from "@skill-spark/skill-core/output";
import { scanTracked } from "@skill-spark/skill-core/tracked";
import pc from "picocolors";

export const COMMAND_DESCRIPTION = "Generate AGENTS.md for AI agent context discovery";
export const COMMAND_EXAMPLES = [
  "skill-spark generate agents-md                        # Generate ./AGENTS.md",
  "skill-spark generate agents-md --output ./docs/AGENTS.md  # Custom output path",
  "skill-spark generate agents-md --scope global             # Only global skills",
  "skill-spark generate agents-md --scope project            # Only project skills",
];
export const COMMAND_PREREQUISITES = [
  "Skills must be tracked in skills.lock",
];

export interface GenerateAgentsOptions {
  output?: string;
  scope?: "global" | "project" | "all";
  force?: boolean;
}

function formatSkillsSection(items: ReturnType<typeof scanTracked>, scopeLabel: string): string {
  const installed = items.filter((i) => i.validInstallations.length > 0);
  const registered = items.filter((i) => i.validInstallations.length === 0);

  if (items.length === 0) return "";

  let section = `## Skills (${scopeLabel})\n\n`;

  if (installed.length > 0) {
    section += `### Installed\n\n`;
    for (const item of installed) {
      const agents = item.validInstallations.map((inst) => inst.agent).join(", ");
      section += `- **${item.type}:${item.name}** — available in: ${agents}\n`;
    }
    section += "\n";
  }

  if (registered.length > 0) {
    section += `### Registered (not installed)\n\n`;
    for (const item of registered) {
      section += `- **${item.type}:${item.name}** — run \`skill-spark add ${item.url}\` to install\n`;
    }
    section += "\n";
  }

  // Trigger phrases for AI agents
  if (installed.length > 0) {
    section += `### How to Use\n\n`;
    section += `When the user mentions any of these skill names or their related topics, consult the corresponding SKILL.md in the agent's skills directory for detailed instructions.\n\n`;

    section += `| Skill | Trigger Phrases |\n`;
    section += `|-------|----------------|\n`;
    for (const item of installed) {
      section += `| ${item.type}:${item.name} | \`${item.name}\` related tasks |\n`;
    }
    section += "\n";
  }

  return section;
}

export async function handleGenerateAgents(options: GenerateAgentsOptions) {
  showIntro();

  try {
    const allItems = scanTracked();

    // Filter by scope
    let items = allItems;
    if (options.scope === "global") {
      items = allItems.filter((i) => i.scope === "global");
    } else if (options.scope === "project") {
      items = allItems.filter((i) => i.scope === "project");
    }

    if (items.length === 0) {
      p.log.warn("No tracked skills found.");
      showOutro(pc.yellow("Nothing to generate"));
      return;
    }

    const outputPath = options.output ?? join(process.cwd(), "AGENTS.md");

    let content = `# AGENTS.md — AI Agent Context

> Auto-generated by skill-spark. This file helps AI coding agents discover available skills and how to use them.
> Regenerate with: \`skill-spark generate agents-md\`

---

`;

    const globalItems = items.filter((i) => i.scope === "global");
    const projectItems = items.filter((i) => i.scope === "project");

    if (options.scope === "global" || options.scope === "all" || (!options.scope && globalItems.length > 0)) {
      content += formatSkillsSection(globalItems, "Global");
    }

    if (options.scope === "project" || options.scope === "all" || (!options.scope && projectItems.length > 0)) {
      content += formatSkillsSection(projectItems, "Project");
    }

    // Skill management commands section
    if (items.length > 0) {
      content += `## Skill Management

The \`skill-spark\` CLI manages all installed skills:

| Command | Description |
|---------|-------------|
| \`skill-spark list\` | List all tracked skills and their status |
| \`skill-spark add <source>\` | Install skills from a source |
| \`skill-spark register <source>\` | Register a skill source (without installing) |
| \`skill-spark remove <name>\` | Remove a skill (default: global scope) |
| \`skill-spark remove <name> --project\` | Remove a project-scoped skill |
| \`skill-spark update [name]\` | Update skills to latest version |
| \`skill-spark search [query]\` | Search the skills registry |

`;
    }

    // Auto-generated footer
    content += `---
*Generated by skill-spark on ${new Date().toISOString().split("T")[0]}*\n`;

    const confirmed = options.force
      ? true
      : await (async () => {
          p.log.info(`Will write to: ${pc.cyan(outputPath)}`);
          const result = await p.confirm({ message: "Generate AGENTS.md?" });
          return !p.isCancel(result) && result;
        })();

    if (!confirmed) {
      p.cancel("Generation cancelled");
      return;
    }

    writeFileSync(outputPath, content, "utf-8");

    const installedCount = items.filter((i) => i.validInstallations.length > 0).length;
    const registeredCount = items.filter((i) => i.validInstallations.length === 0).length;

    p.log.success(pc.green(`AGENTS.md generated at ${outputPath}`));
    p.log.info(
      `${pc.green(installedCount.toString())} installed, ${pc.yellow(registeredCount.toString())} registered`,
    );

    showOutro(pc.green("AGENTS.md ready"));
  } catch (error) {
    p.log.error(getError(error, "Something went wrong."));
    showOutro(pc.red("Generation failed"));
    process.exit(1);
  }
}
